### ISSUE TITLE
Consideration: binary data folder location / R-package

### ISSUE THREAD

**Issue by florisvdh** [inbo/n2khab-inputs#2]
- binary data folder outside repo `../n2khab-binarydata` could also be replaced by an _ignored_ subfolder `binary` in `data/10_raw`. However, that may conflict with the next consideration.
- the repo could be distributed as R-package as a user-friendly way to share the functions (see `functionality.md` to get a flavour). I need to look further into that (Hadley's book). To consider is what would be the effect on the data folder:
  - it is not wise to distribute the binary data with the package -- relevant if the preceding point is implemented. It should be possible to exclude these data from package building & installation.
  - regarding textual input data, it could be an advantage to have them within the package -- it just concerns important checklists, so it would be cool to distribute them along.

Any thoughts on this, @stijnvanhoey?

**Comment by stijnvanhoey** [comment]
I like to have a single project folder containing all material, so I would opt for an _git ignored_ binary data folder inside the repo in combination with functions/documentation to get retrieve the data (cfr. inimal example [in wmh analysis](https://github.com/inbo/wmh-analysis/tree/addREADME#external-gis-data-available-through-web-links).

As you say, this indeed clashes with the R package idea. Still, you can have an R package as a subfolder of the repo as well, as we did for the [grofwildjacht](https://github.com/inbo/reporting-rshiny-grofwildjacht) with the [reporting-grofwild subfolder](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/master/reporting-grofwild). Installing the package is done with the `subdir` argument. By doing so, you can integrate a package inside the repo to collect all functionalities, but have the main structure of a typical _data science_ project:

```
├── data
├── src
    ├── ...
    └── analysis
├── n2khab-input-package
├── README.md
└── LICENSE
```
or 
```
├── data
├── src
    ├── n2khab-input-package
    ├── ...
    └── analysis
├── README.md
└── LICENSE
```

**Comment by florisvdh** [comment]
Thanks a lot for your ideas @stijnvanhoey . I'll think about the package approach.

Other topics:

- retrieving external GIS-data: referring is the approach I envisage as well, i.e. defining the authorative source location (typically external) while requiring to have a local copy (which may be republished to ensure long-term availability and therefore reproducibility). An automatic retrieval is indeed an option but not so urgent to implement.
- the one versus several repositories consideration: this is not one data science project; at least the data and functions within this `n2khab-inputs` repo will serve several Natura 2000 habitat related projects. The same holds for the other repos, e.g. `n2khab-samplingframes` will serve both the `n2khab-mne-design` and `n2khab-mhq-design` projects. So the scopes differ. There is one common scope though, Natura 2000 habitat (**N2KHAB**), but you could compare that with a level like (at least) TRIAS. Perhaps we could put the n2khab-repos apart in the future under a 'project' at the inbo-github page, but that is no urgent matter.

**Comment by hansvancalster** [comment]
I second @stijnvanhoey: better to keep everything in one folder and thus use a gitignored folder for large files.

**Comment by florisvdh** [comment]
I've been looking into packaging and I think one of below pictured repo structures will work best. It follows the suggestion of @stijnvanhoey (package in subfolder).

To me it seems quite evident that we should pack the functions into an R-package in order to make them easily available to several n2khab-projects (see generalized [scheme](https://drive.google.com/file/d/1RQsjxch0YKdqJSPIDjCG_wEbYTlP3oDv/view)).

My preferred option is the first one, as we would be distributing _and versioning_ binary RData-files with the second option, even though these files could in general be small: derived from text files -- but still, this can grow in the future, I may underestimate this. (And I presume we won't all start using git LFS to overcome that.)
```
├── data                 <- Binary data! Copy needed data here. Ignored by git.
    ├── 10_raw
    ├── 20_processed     <- Either copy from a source location, or generate yourself.
├── src                  <- Scripts / R markdown files
├── n2khabflanders       <- R-package
    ├── inst
        ├── textdata     <- Textual data delivered with the package.
                            Will be read into R using git2rdata::read_vc()
    ├── man
    ├── R                <- Functions are written here.
    ├── DESCRIPTION
    ├── NAMESPACE
    ├── LICENSE
├── functionality.md     <- Functionality needed for this repo and associated n2khab-repos
├── n2khab-inputs.Rproj  <- RStudio project file
├── README.md
└── LICENSE
```

or

```
├── data                 
    ├── binary           <- Binary data. Copy needed data in the right folder. Ignored by git.
        ├── 10_raw
        ├── 20_processed <- Either copy from a source location, or generate yourself.
    ├── text             <- Textual data. Will be packaged in the R package as R objects.
        ├── 10_raw
        ├── 20_processed
├── src                  <- Scripts / R markdown files
├── n2khabflanders       <- R-package
    ├── data             <- RData files derived from the textual data
                            and delivered with the package
    ├── man
    ├── R                <- Functions are written here.
    ├── DESCRIPTION
    ├── NAMESPACE
    ├── LICENSE
├── functionality.md     <- Functionality needed for this repo and associated n2khab-repos
├── n2khab-inputs.Rproj  <- RStudio project file
├── README.md
└── LICENSE
```

Notes for further reference (and mostly referring to the first option):

- textual data (i.e. basic reference lists) go within the package (`n2khabflanders/inst/textdata`), in order to distribute them more easily
- binary data do not go within the package, so these data still reside in another, top-level folder. In fact this more or less moves the original setup (see readme at b67118b) one level lower, within this repo. _For reference: reasons for not putting that (git-ignored) large-files-folder within the package (in `n2khabflanders/inst/extdata/binary/10_raw`):_
  - _while it is possible not to withhold such a folder in the package build process (by listing it in `.Rbuildignore`), referring to it from within an R script (either in `src` or in `../another-n2khab-project/src`) would require a rather long, awkward path, as it is quite deeply nested in the repo._
    - _note that this disadvantage does not occur with the text files, distributed with the package, as these can be called with `system.file()`, which can be used as the default path for functions that read those files._
  - _the alternative, to effectively let it be part of the build process (while still git-ignoring it, so user always needs to put data in place first), would make the user have two copies of that folder on his/her computer (one in the local repo, one in the installed package), which is overkill. To me, it seems not good practice at all to pack large data within an R package._
- as package names [should not contain hyphens](https://r-pkgs.org/package-structure.html#requirements-for-a-name), while it _is_ [our naming convention](https://inbo.github.io/tutorials/tutorials/styleguide_repos/) for git repositories, I propose to name the R-package _n2khabflanders_. Better suggestions are welcome. In an international context, I thought it is important to stress both 'Natura 2000 habitat' (as opposed to species) and 'Flanders'. Shorter versions could be _habflanders, flandershab, flandershabr, habflandersr_ and the like. You're welcome to mention your favourite.
- as already foreseen, the folder `src` will contain a few more generic (rather project-agnostic) 'n2khab' workflows (R scripts or R markdown), such as installing the package, updating some of the text data, datachecks for the workflows and the creation of some of the (generated) binary data.

**Comment by florisvdh** [comment]
@stijnvanhoey, what is your preference: the first or the second repository + package structure (above)? The difference is in the position of the textual data and in the (non-)creation of RData objects from it.

BTW, a list of functions being thought of, can be found [here](https://docs.google.com/spreadsheets/d/18U4AmiMnnApbgQTnfWbeZ3dAH3_4ISxUob_SX-maKV8/edit#gid=924567109); descriptions are [here](https://github.com/inbo/n2khab-inputs/blob/add_functionality_requirements/functionality.md).

**Comment by stijnvanhoey** [comment]
If sizes are not too big, I would opt the first one: (1) no double data in the repo, (2) not having to think about updating .Rdata and (3) data is also visible as such checking the package.

Still, I would just start implementing and see how it ends up. Rearranging is still possible on a later moment if required. Just go for it

**Comment by florisvdh** [comment]
Thanks @stijnvanhoey! Having the same preference, I'll decide as such, and - indeed - we can start implementing.  Hence, issue closed.

**Comment by florisvdh** [comment]
Just adding here that I chose the name `n2khabutils` for the R-package. Other suggestions are welcome.
